id: A04F034F5
title: 'The Swift Fulfillment of All Wishes (Sampa Nyur Drupma): A Prayer to Master
  Padmasambhava'
type: translation
pechas:
- I4D4CC40B
- I3D1B5F8C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:59:40.955341
  last_modified_at: 2023-01-04 11:59:40.955352
  collections:
  - Jamgön Amnye Zhab Series
  - Works of Tibetan Masters
alignment_to_base:
  I4D4CC40B/CABB: BB21
  I3D1B5F8C/7191: BB21
